apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment  # Name of the deployment
spec:
  replicas: 3  # Number of replicas/pods you want to run
  selector:
    matchLabels:
      app: my-node-app  # Label selector to match with the pods
  template:
    metadata:
      labels:
        app: my-node-app  # Apply the label for identification
    spec:
      containers:
        - name: my-node-app-container  # Container name
          image: sajeebchandradas/my-node-app:latest  # Use the actual Docker image for your app
          ports:
            - containerPort: 8000  # Port where the app listens inside the containe
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service  # The name of the service within the cluster
spec:
  selector:
    app: my-node-app  # Match the selector with the deployment label
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service within the cluster
      targetPort: 8000  # Port your app is listening on inside the container
  type: LoadBalancer  # Use LoadBalancer to expose your app to the outside world
