apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-cicd-deployment  # Name of the deployment
spec:
  replicas: 3  # Number of replicas/pods you want to run
  selector:
    matchLabels:
      app: node-todo-cicd  # Label selector to match with the pods
  template:
    metadata:
      labels:
        app: node-todo-cicd  # Apply the label for identification
    spec:
      containers:
        - name: node-todo-cicd-container  # Container name
          image: sajeebchandradas/node-todo-cicd:latest  # Use the actual Docker image for your app
          ports:
            - containerPort: 8000  # Port where the app listens inside the containe
---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-cicd-service  # The name of the service within the cluster
spec:
  selector:
    app: node-todo-cicd  # Match the selector with the deployment label
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service within the cluster
      targetPort: 8000  # Port your app is listening on inside the container
  type: LoadBalancer  # Use LoadBalancer to expose your app to the outside world
